### ISSUE TITLE
Confused about labels

### ISSUE THREAD

**Issue by wezm** [jonhoo/faktory-rs#7]
Hi [the documentation](https://github.com/jonhoo/faktory-rs/blob/838f4cac2be119d0213ff9a79b0b8a8523b2c75b/src/producer/mod.rs#L41) mentions a "labels" field on `Job` however as far as I can tell there is no such field. Is the documentation incorrect or is there another detail I'm missing?

**Comment by jonhoo** [comment]
You're [totally right](https://github.com/contribsys/faktory/issues/34#issuecomment-339585993)! Fixed in 0.9.2. You may also want to submit a PR to the main Faktory repository and suggest that [the relevant protocol specs](https://github.com/contribsys/faktory/blob/03aad4639a187f13ecbcfd63b8a27794a0311502/docs/protocol-specification.md#required-fields-for-consumers) are also updated :)

**Comment by wezm** [comment]
Great, thanks for the quick response :+1:
